name: Compile, Upload and Release Typst Documents
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            aaron_murniadi_cv.typ
      
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: *.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: main.pdf