name: Compile, Upload and Release Typst Documents
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            aaron_murniadi_cv.typ
      
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: aaron_murniadi_cv.pdf
          path: aaron_murniadi_cv.pdf

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Automated build v${{ github.run_number }}
          files: aaron_murniadi_cv.pdf
          generate_release_notes: true